kind: RoleBinding

apiVersion: rbac.authorization.k8s.io/v1

metadata:

  name: pod-reader-access

subjects:

- kind: User

  name: jenkins

  apiGroup: rbac.authorization.k8s.io

roleRef:

  kind: Role

  name: managepods

  apiGroup: rbac.authorization.k8s.io